import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "The Kazemis - 14/05/2024 - Valle di Badia, Tuscany, Italy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html style={{ backgroundImage: "url('/bg-pattern.png')" }} lang="en">
      <body style={{ backgroundColor: '#fffffff0' }} className={inter.className}>{children}</body>
    </html>
  );
}
